---
# This role installs opendj. It will listen on the default ports (389/636 for ssl)
# Assumes 'java' is installed and on the path
# TODO: Import sample ldif, schema
#

# download or used cached copy
- include: ../../download.yml download_file={{opendj_zip}} download_url={{opendj_download_url}}

- lineinfile: dest="/etc/hosts" line="127.0.0.1 {{opendj_fqdn}}"

- name: stop opendj
  service: name=opendj state=stopped
  ignore_errors: no

- name: wait for opendj to stop
  wait_for: host=0.0.0.0 port={{opendj_admin_port}} delay=30 state=drained

- name: remove any old opendj instance 
  file: path={{install_root}}/opendj state=absent

- name: create install root
  file: path={{install_root}}/opendj state=directory

- name: unpack opendj
  unarchive: src={{ download_dir }}/{{ opendj_zip }} dest={{install_root}} copy=no

- name: create service directories
  file: path={{item}} state=directory
  with_items:
    - "{{install_root}}/opendj/logs"
    - "{{install_root}}/opendj/locks"

- name: copy opendj props file
  template: src=opendj.properties dest=/tmp/opendj.properties 

- name: setup opendj
  command: creates={{install_root}}/opendj/config {{install_root}}/opendj/setup --cli --propertiesFilePath /tmp/opendj.properties --acceptLicense --no-prompt --doNotStart

- name: Create rc script
  command: "{{install_root}}/opendj/bin/create-rc-script -f /etc/init.d/{{opendj_service_name}} -u root"

- name: Change the ownership on the files so the fr user can execute ldap commands
  file: path={{install_root}}/opendj state=directory owner={{fr_user}} recurse=yes

# Ignore errors as the installer may start DJ
- name: Start opendj
  service: name={{opendj_service_name}} state=started enabled=yes
  ignore_errors: yes


- name: Create base suffix for opendj config store. This makes it easier if we want to use OpenAM later
  command: "{{install_root}}/opendj/bin/dsconfig set-backend-prop --backend-name userRoot --add base-dn:{{opendj_basedn}}
    --hostname localhost --port {{opendj_admin_port}} --bindDN cn=\"Directory\ Manager\" --bindPassword {{opendj_password}}
    --trustAll --noPropertiesFile --no-prompt"
