# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

SSOADM="{{install_root}}/ssoadmin/openam"

PATH=$PATH:$HOME/bin:$SSOADM/bin

export PATH