#!/bin/bash
# Enable the REST interface for OpenDJ
# TODO: Make this take arguments

$PASSWORD=$PASSWORD

DSCONFIG=/opt/opendj/bin/dsconfig

$DSCONFIG set-connection-handler-prop \
 --hostname openam.example.com \
 --port 4444 \
 --bindDN "cn=Directory Manager" \
 --bind$PASSWORD $PASSWORD \
 --handler-name "HTTP Connection Handler" \
 --set enabled:true \
 --no-prompt \
 --trustAll \
 
 # Enable log 
 $DSCONFIG  set-log-publisher-prop \
 --hostname openam.example.com \
 --port 4444 \
 --bindDN "cn=Directory Manager" \
 --bind$PASSWORD $PASSWORD \
 --publisher-name "File-Based HTTP Access Logger" \
 --set enabled:true \
 --no-prompt \
 --trustAll
 
$DSCONFIG set-trust-manager-provider-prop \
 --hostname openam.example.com \
 --port 4444 \
 --bindDN "cn=Directory Manager" \
 --bind$PASSWORD $PASSWORD \
 --provider-name "Blind Trust" \
 --set enabled:true \
 --no-prompt \
 --trustAll
 
$DSCONFIG set-connection-handler-prop \
 --hostname openam.example.com \
 --port 4444 \
 --bindDN "cn=Directory Manager" \
 --bind$PASSWORD $PASSWORD \
 --handler-name "HTTP Connection Handler" \
 --set listen-port:38443  \
 --set use-ssl:true \
 --set key-manager-provider:JKS \
 --set trust-manager-provider:"Blind Trust" \
 --no-prompt \
 --trustAll
 
 # Sample to test access
 # curl -k --user user.0:password https://openam.example.com:38443/users/user.0?_prettyPrint=true